// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtEW1o4x_VNbca3V9zfb2PYkYnzlcHB8E',
    appId: '1:984090547439:web:b76343c5a0e97ece1b771a',
    messagingSenderId: '984090547439',
    projectId: 'meldep-dev',
    authDomain: 'meldep-dev.firebaseapp.com',
    storageBucket: 'meldep-dev.firebasestorage.app',
    measurementId: 'G-62Z57F614Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIoSC2pzqtJG8ed-tu3mv-uY-Dx-GejA',
    appId: '1:984090547439:android:c8cba76ff9b59efe1b771a',
    messagingSenderId: '984090547439',
    projectId: 'meldep-dev',
    storageBucket: 'meldep-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbXzftxpt3XIxcGsHu24fk_8uj8XqIh9k',
    appId: '1:984090547439:ios:3bbe11a7d683773f1b771a',
    messagingSenderId: '984090547439',
    projectId: 'meldep-dev',
    storageBucket: 'meldep-dev.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbXzftxpt3XIxcGsHu24fk_8uj8XqIh9k',
    appId: '1:984090547439:ios:3bbe11a7d683773f1b771a',
    messagingSenderId: '984090547439',
    projectId: 'meldep-dev',
    storageBucket: 'meldep-dev.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtEW1o4x_VNbca3V9zfb2PYkYnzlcHB8E',
    appId: '1:984090547439:web:287079d3c93a24f71b771a',
    messagingSenderId: '984090547439',
    projectId: 'meldep-dev',
    authDomain: 'meldep-dev.firebaseapp.com',
    storageBucket: 'meldep-dev.firebasestorage.app',
    measurementId: 'G-5Y50ZRYBBC',
  );
}
