// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_uat.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMiUpSNfBn2SZT-WHm6vx5u4suyaOGKw',
    appId: '1:352903349747:web:81e1eceda4637151ecbe86',
    messagingSenderId: '352903349747',
    projectId: 'meldep-uat',
    authDomain: 'meldep-uat.firebaseapp.com',
    storageBucket: 'meldep-uat.firebasestorage.app',
    measurementId: 'G-K3RFZ0V3GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTcYWkJUzZwJwuB2uf7MPcKwM15HnQxWw',
    appId: '1:352903349747:android:fc5342d5423d4054ecbe86',
    messagingSenderId: '352903349747',
    projectId: 'meldep-uat',
    storageBucket: 'meldep-uat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFMGN9G6hQGtZ3kIwmyiejbRuJaG5jbo',
    appId: '1:352903349747:ios:7f7416c0c494f3c6ecbe86',
    messagingSenderId: '352903349747',
    projectId: 'meldep-uat',
    storageBucket: 'meldep-uat.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFMGN9G6hQGtZ3kIwmyiejbRuJaG5jbo',
    appId: '1:352903349747:ios:7f7416c0c494f3c6ecbe86',
    messagingSenderId: '352903349747',
    projectId: 'meldep-uat',
    storageBucket: 'meldep-uat.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMiUpSNfBn2SZT-WHm6vx5u4suyaOGKw',
    appId: '1:352903349747:web:717bc31ccfe86ae1ecbe86',
    messagingSenderId: '352903349747',
    projectId: 'meldep-uat',
    authDomain: 'meldep-uat.firebaseapp.com',
    storageBucket: 'meldep-uat.firebasestorage.app',
    measurementId: 'G-WVEBW6T0M4',
  );
}
