// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvH0vPaGnJSfCunrhCn_XBZj0IJjfyAOc',
    appId: '1:838559461497:web:df0378d0512707b30aa4a8',
    messagingSenderId: '838559461497',
    projectId: 'meldep',
    authDomain: 'meldep.firebaseapp.com',
    storageBucket: 'meldep.firebasestorage.app',
    measurementId: 'G-710BD3N3FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfHzup1I7LOFHD-dDaoKkG97N8sB4d_mw',
    appId: '1:838559461497:android:0be8e1d76f17d7830aa4a8',
    messagingSenderId: '838559461497',
    projectId: 'meldep',
    storageBucket: 'meldep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsErq-Dc-oaqenTctVgarFqAaFbJUN9HU',
    appId: '1:838559461497:ios:7a63d27a9854161a0aa4a8',
    messagingSenderId: '838559461497',
    projectId: 'meldep',
    storageBucket: 'meldep.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsErq-Dc-oaqenTctVgarFqAaFbJUN9HU',
    appId: '1:838559461497:ios:7a63d27a9854161a0aa4a8',
    messagingSenderId: '838559461497',
    projectId: 'meldep',
    storageBucket: 'meldep.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvH0vPaGnJSfCunrhCn_XBZj0IJjfyAOc',
    appId: '1:838559461497:web:d497c359285c7dc10aa4a8',
    messagingSenderId: '838559461497',
    projectId: 'meldep',
    authDomain: 'meldep.firebaseapp.com',
    storageBucket: 'meldep.firebasestorage.app',
    measurementId: 'G-ERQCJLVQ52',
  );
}
